from __future__ import annotations

from typing import Protocol

from contracts.pipeline import CompareResult, CompareSnapshot


class DecisionProvider(Protocol):
    """Scenario-neutral boundary implemented by a concrete decision service."""

    async def initialize(self) -> None: ...
    async def warmup(self) -> None: ...
    async def decide(self, snapshot: CompareSnapshot) -> CompareResult: ...
    async def aclose(self) -> None: ...


class CandidateProposer(Protocol):
    def load(self) -> dict: ...
    def warmup(self) -> None: ...
    def propose_snapshot(self, text: str) -> CompareSnapshot: ...
    def close(self) -> None: ...
